### ISSUE TITLE
Remove sample articles

### ISSUE THREAD

**Issue by AlexHff** [hoffmann-ai/website#14]
Remove all of the sample articles in latin from the blog page.

**Comment by Ines-ux-dev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HOFFMANN.AI] Remove sample articles](https://trello.com/c/KHDQ6tI8/59-hoffmannai-remove-sample-articles)

**Comment by AlexHff** [comment]
Thank you.
