### ISSUE TITLE
Default template links are orange on hover

### ISSUE THREAD

**Issue by dextmorgn** [hoffmann-ai/website#20]
Links on hover/active are orange (default template).

**Expected behavior**
Links on hover/active should be blue (#0873e8)

**Comment by AlexHff** [comment]
@EliottElek Did you fix the current implementation? You mentioned issues as well as a fix.

**Comment by dextmorgn** [comment]
This issue has been fixed on latest Jacques's PR (landing implementation) 
This PR was the fusion of our work on the landing page and the issue has been fixed there. 
The fix is not yet on master branch.
