### ISSUE TITLE
Update metadata

### ISSUE THREAD

**Issue by AlexHff** [hoffmann-ai/website#25]
**Is your feature request related to a problem? Please describe.**
Site metadata is not up to date. Favicon, description, title, etc. are still in their original form.

**Describe the solution you'd like**
- Find out all the necessary fields to fill
- Make a request to get the information
- Update the site metadata.

**Comment by AlexHff** [comment]
```json
{
    "allSite": {
      "edges": [
        {
          "node": {
            "siteMetadata": {
              "copyright": "© All rights reserved.",
              "description": null,
              "disqusShortname": "",
              "logo": "/logo.png",
              "menu": [
                {
                  "label": "Blog",
                  "path": "/blog"
                },
                {
                  "label": "A propos",
                  "path": "/about"
                },
                {
                  "label": "Contact",
                  "path": "/contact"
                }
              ],
              "subtitle": "Pellentesque odio nisi, euismod in, pharetra a, ultricies in, diam. Sed arcu.",
              "title": "HOFFMANN.AI",
              "url": "https://hoffmann.ai",
              "author": {
                "bio": "Pellentesque odio nisi, euismod in, pharetra a, ultricies in, diam. Sed arcu.",
                "name": "Alexander Hoffmann",
                "photo": "/photo.jpg",
                "contacts": {
                  "codepen": "",
                  "email": "",
                  "facebook": "",
                  "github": "",
                  "gitlab": "",
                  "line": "",
                  "instagram": "",
                  "linkedin": "",
                  "medium": "",
                  "rss": "",
                  "soundcloud": "",
                  "telegram": "",
                  "twitter": "",
                  "weibo": "",
                  "vkontakte": "",
                  "youtube": ""
                }
              }
            }
          }
        }
      ]
    }
  }
```

**Comment by AlexHff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HOFFMANN.AI] Update metadata](https://trello.com/c/L2SPAl6Z/105-hoffmannai-update-metadata)

**Comment by Ines-ux-dev** [comment]
Renvoi à la ligne automatique
--
  | <!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><meta name="note" content="environment=development"/><link rel="alternate" type="application/rss+xml" title="HOFFMANN.AI" href="/rss.xml"/><style type="text/css">
  | .anchor.before {
  | position: absolute;
  | top: 0;
  | left: 0;
  | transform: translateX(-100%);
  | padding-right: 4px;
  | }
  | .anchor.after {
  | display: inline-block;
  | padding-left: 4px;
  | }
  | h1 .anchor svg,
  | h2 .anchor svg,
  | h3 .anchor svg,
  | h4 .anchor svg,
  | h5 .anchor svg,
  | h6 .anchor svg {
  | visibility: hidden;
  | }
  | h1:hover .anchor svg,
  | h2:hover .anchor svg,
  | h3:hover .anchor svg,
  | h4:hover .anchor svg,
  | h5:hover .anchor svg,
  | h6:hover .anchor svg,
  | h1 .anchor:focus svg,
  | h2 .anchor:focus svg,
  | h3 .anchor:focus svg,
  | h4 .anchor:focus svg,
  | h5 .anchor:focus svg,
  | h6 .anchor:focus svg {
  | visibility: visible;
  | }
  | </style><script>
  | document.addEventListener("DOMContentLoaded", function(event) {
  | var hash = window.decodeURI(location.hash.replace('#', ''))
  | if (hash !== '') {
  | var element = document.getElementById(hash)
  | if (element) {
  | var scrollTop = window.pageYOffset \|\| document.documentElement.scrollTop \|\| document.body.scrollTop
  | var clientTop = document.documentElement.clientTop \|\| document.body.clientTop \|\| 0
  | var offset = element.getBoundingClientRect().top + scrollTop - clientTop
  | // Wait for the browser to finish rendering before scrolling.
  | setTimeout((function() {
  | window.scrollTo(0, offset - 0)
  | }), 0)
  | }
  | }
  | })
  | </script><link rel="sitemap" type="application/xml" href="/sitemap.xml"/><link rel="icon" href="/favicon-32x32.png?v=0c8fafc8bef8cc5e681b4713fc1affdb" type="image/png"/><link rel="manifest" href="/manifest.webmanifest" crossorigin="anonymous"/><meta name="theme-color" content="#F7A046"/><link rel="apple-touch-icon" sizes="48x48" href="/icons/icon-48x48.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"/><link rel="apple-touch-icon" sizes="72x72" href="/icons/icon-72x72.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"/><link rel="apple-touch-icon" sizes="96x96" href="/icons/icon-96x96.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"/><link rel="apple-touch-icon" sizes="144x144" href="/icons/icon-144x144.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"/><link rel="apple-touch-icon" sizes="192x192" href="/icons/icon-192x192.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"/><link rel="apple-touch-icon" sizes="256x256" href="/icons/icon-256x256.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"/><link rel="apple-touch-icon" sizes="384x384" href="/icons/icon-384x384.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"/><link rel="apple-touch-icon" sizes="512x512" href="/icons/icon-512x512.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"/><title data-react-helmet="true"></title><script src="/socket.io/socket.io.js"></script></head>

**Comment by Ines-ux-dev** [comment]
<head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><meta name="note" content="environment=development"/><link rel="alternate" type="application/rss+xml" title="HOFFMANN.AI" href="/rss.xml"/><style type="text/css">

**Comment by Ines-ux-dev** [comment]
meta charSet="utf-8"
meta http-equiv="x-ua-compatible" content="ie=edge"
meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
meta name="note" content="environment=development"
link rel="alternate" type="application/rss+xml" title="HOFFMANN.AI" href="/rss.xml"
style type="text/css"
link rel="sitemap" type="application/xml" href="/sitemap.xml"
link rel="icon" href="/favicon-32x32.png?v=0c8fafc8bef8cc5e681b4713fc1affdb" type="image/png"
link rel="manifest" href="/manifest.webmanifest" crossorigin="anonymous"
meta name="theme-color" content="#F7A046"
link rel="apple-touch-icon" sizes="48x48" href="/icons/icon-48x48.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"
link rel="apple-touch-icon" sizes="72x72" href="/icons/icon-72x72.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"
link rel="apple-touch-icon" sizes="96x96" href="/icons/icon-96x96.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"
link rel="apple-touch-icon" sizes="144x144" href="/icons/icon-144x144.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"
link rel="apple-touch-icon" sizes="192x192" href="/icons/icon-192x192.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"
link rel="apple-touch-icon" sizes="256x256" href="/icons/icon-256x256.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"
link rel="apple-touch-icon" sizes="384x384" href="/icons/icon-384x384.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"
link rel="apple-touch-icon" sizes="512x512" href="/icons/icon-512x512.png?v=0c8fafc8bef8cc5e681b4713fc1affdb"
title data-react-helmet="true"></title><script src="/socket.io/socket.io.js"

**Comment by AlexHff** [comment]
Done. Thanks.
