### ISSUE TITLE
Real-time conversations widget

### ISSUE THREAD

**Issue by AlexHff** [hoffmann-ai/website#31]
**Is your feature request related to a problem? Please describe.**
Increase website conversion with chatbots, and grow revenue through real-time conversations.

**Describe the solution you'd like**
Real-time chat to respond to current and/or future customers. Create a state of the art for solutions with price and feature comparison.

**Comment by AlexHff** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HOFFMANN.AI] Real-time conversations widget](https://trello.com/c/m7sohBJe/106-hoffmannai-real-time-conversations-widget)

**Comment by zoecrouzet** [comment]
[Real time chat widget - state of art.pdf](https://github.com/hoffmann-ai/website/files/6846258/Real.time.chat.widget.-.state.of.art.pdf)

**Comment by AlexHff** [comment]
Done. Thanks.
